### ISSUE TITLE
Sonar scanner doesn't find any 'flutter analyze' issues during scan

### ISSUE THREAD

**Issue by seanhumessonos** [insideapp-oss/sonar-flutter#154]
I'm having difficulty getting the sonar-scanner to identify the lint failures in my dart code. I've gone through the documentation to install flutter on linux and the plugins readme and I'm not sure what I'm missing?

Repo:
In my container, I can successfully call 'flutter analyze' and see I have two failures that I have made:

```
root@cd50b81ae570:/flutter_setup/module# flutter analyze
Analyzing module...

   info • Sort directive sections alphabetically • lib/main.dart:11:1 • directives_ordering
   info • Avoid `print` calls in production code • lib/main.dart:39:3 • avoid_print

2 issues found. (ran in 1.9s)
```

I run my sonar-scanner with my sonar-project.properties file and my analysis_options.yaml

```
# sonar-project.properties
sonar.projectKey=my_project
sonar.projectName=My Project
sonar.projectVersion=1.0
sonar.login=<token>
sonar.dart.analysis.useExistingOptions=true
sonar.sources=lib
sonar.tests=test_driver
sonar.sourceEncoding=UTF-8
sonar.flutter.analyzer.mode=flutter
```

```
# analysis_options.xml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [some_file.dart]

  errors:
    no_logic_in_create_state: ignore

linter:
  # Our additional rules on top of the default settings
  rules:
    # Style rules
    - directives_ordering
    # Usage rules
    - prefer_interpolation_to_compose_strings
    - prefer_expression_function_bodies
    - unnecessary_parenthesis
    - unnecessary_lambdas
```

but I end up getting no issues found in the sonar scanner:

```
INFO: Sensor Dart sensor [flutter] (done) | time=1781ms
INFO: Sensor dartanalyzer sensor [flutter]
INFO: Chosen analyzer mode: flutter
INFO: Running 'flutter analyze'...
INFO: Found issues: 0
INFO: Sensor dartanalyzer sensor [flutter] (done) | time=3035ms
```

Environment:
- Linux 20.04
- Flutter 3.3.8
- SonarQube 8.9.9
- Flutter plugin 0.4.0
- sonar-scanner 4.7.0

Note: I'm not using the latest Flutter or SonarQube versions so maybe that is my problem? I'm unfortunately constrained by the current environment but if it is related to those version I would greatly appreciate any notes or bugs I may have missed.
